CREATE DATABASE IF NOT EXISTS cryptodb;

USE cryptodb;

CREATE TABLE IF NOT EXISTS users (
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(60) NOT NULL,
    created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (email)
)